ci(workflow): Add hadolint job (#7)
`hadolint` で _Containerfile_ の書式チェックするジョブを追加。
結果を `reviewdog` で報告する。

- fix(workflow): Check hadlint failure
  _Lint_ 対象のファイルが変更されていない場合、 `reviewdog` による失敗判定 (`-fail-level`) がうまくいかないので
  `hadolint` でも失敗判定をした上で最後のステップでジョブを失敗/成功させる。

- refactor(workflow): Simplification reviewdog commands
  `reviewdog` コマンドを整理。

- style(workflow): Add ruleId to message text 
  SARIF ファイルの `ruleId` が `reviewdog` のコメントに表示されなかったので、
  `jq` コマンドを通して `.message.text` に埋め込んだ。

- refactor(containerfile): Apply Hadolint best practices 
  - Add a new line before a commnet (DL1000)
  - Use `wget` option `-q` (DL3047)
  - Ignore pin versions in apt get install (DL3008)
  - Ignore unused variable in RUN shellscript (SC2034)

- refactor(containerfile): Refactor to download s6-overlay
  Improved _case_ statement.

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -25,9 +25,96 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+  lint-containerfile:
+    name: Scan the Containerfile
+    runs-on: ubuntu-24.04
+    permissions:
+      contents: read
+      # プルリクエスト操作許可
+      pull-requests: write
+      checks: write
+      # セキュリティスキャン結果のアップロード許可
+      security-events: write
+    env:
+      HADOLINT_OUTPUT_FILE: hadolint-report.sarif
+      CI_BRANCH: ${{ github.ref_name }}
+      CI_COMMIT: ${{ github.sha }}
+      CI_REPO_OWNER: ${{ github.repository_owner }}
+      CI_REPO_NAME: ${{ github.event.repository.name }}
+      # メッセージテキストに `ruleId` を付加
+      JQ_FILTER_FOR_SARIF: >-
+        .runs[].results[] |= (.ruleId as $rule | .message.text |= ($rule + ": " + .))
+      REVIEWDOG_CMD: >-
+        reviewdog
+        -name="${REVIEWDOG_NAME:=hadolint}"
+        -f="${REVIEWDOG_INPUT_FORMAT:=sarif}"
+        -reporter="${REVIEWDOG_REPORTER:=github-check}"
+        -filter-mode="${REVIEWDOG_FILTER_MODE:=added}"
+        -fail-level="${REVIEWDOG_FAIL_LEVEL:=warning}"
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      # Install reviewdog
+      # https://github.com/reviewdog/action-setup
+      - name: Setup the reviewdog
+        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
+        with:
+          reviewdog_version: v0.20.3
+
+      # Lint a Containerfile
+      # https://github.com/hadolint/hadolint-action
+      - name: Lint a Containerfile with Hadolint
+        id: hadolint
+        continue-on-error: true
+        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
+        with:
+          dockerfile: Containerfile
+          format: sarif
+          failure-threshold: warning
+          output-file: ${{ env.HADOLINT_OUTPUT_FILE }}
+          ignore: DL3008
+
+      - name: Reviewdog
+        if: ${{ github.event_name != 'pull_request' }}
+        env:
+          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
+          REVIEWDOG_FILTER_MODE: diff_context
+          REVIEWDOG_REPORTER: github-check
+        run: |
+          jq -c "${JQ_FILTER_FOR_SARIF}" ${{ env.HADOLINT_OUTPUT_FILE }} |
+          ${{ env.REVIEWDOG_CMD }}
+
+      - name: Reviewdog (Pull Request)
+        if: ${{ github.event_name == 'pull_request' }}
+        env:
+          CI_BRANCH: ${{ github.head_ref }}
+          CI_PULL_REQUEST: ${{ github.event.pull_request.number }}
+          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
+          REVIEWDOG_FILTER_MODE: diff_context
+          REVIEWDOG_REPORTER: github-pr-review
+        run: |
+          jq -c "${JQ_FILTER_FOR_SARIF}" ${{ env.HADOLINT_OUTPUT_FILE }} |
+          ${{ env.REVIEWDOG_CMD }}
+
+      - name: Check linter exitcode
+        env:
+          HADOLINT_STATUS: ${{ steps.hadolint.outcome }}
+        run: |
+          case "${HADOLINT_STATUS}" in
+            'success')
+              exit 0 ;;
+            'failure')
+              exit 1 ;;
+            *)
+              exit 10 ;;
+          esac
+
   # PR先が main ブランチの場合はレジストリにプッシュしない
   build-multiarch:
     name: Build and Push multi-architecture image
+    needs: lint-containerfile
     strategy:
       fail-fast: false
       matrix:
